name: Track Code Metrics
description: Collect and store code quality metrics for CI/CD pipelines

inputs:
  config-path:
    description: 'Path to umpyre config file'
    default: '.github/umpyre-config.yml'
    required: false
  
  storage-branch:
    description: 'Branch to store metrics'
    default: 'code-metrics'
    required: false
  
  github-token:
    description: 'GitHub token for API access'
    required: true
  
  force-run:
    description: 'Run even if workflow failed'
    default: 'false'
    required: false
  
  python-version:
    description: 'Python version to use'
    default: '3.10'
    required: false

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Install umpyre and dependencies
      shell: bash
      run: |
        pip install umpyre coverage wily bandit interrogate
    
    - name: Collect Metrics
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        python -m umpyre.cli collect \
          --config ${{ inputs.config-path }} \
          --commit ${{ github.sha }}

branding:
  icon: 'bar-chart-2'
  color: 'blue'
